# Implementación de Red Neuronal para clasificación con MLPClassifier

---

**1. Cargamos las librerías**

In [ ]:
# Cargamos las librerías a usar

from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

**2. Carga y exploración de datos**

In [ ]:
# Carga el conjunto de datos de Iris
iris = load_iris()
X, y = iris.data, iris.target

# Explorando los datos
type(iris)
iris.keys()
iris['data']
iris['target']
iris['target_names']
iris['DESCR']
iris['feature_names']


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

**3. Dividimos los datos en conjuntos de entrenamiento y prueba**

In [ ]:
# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

**4. Escalamos las características utilizando StandardScaler para asegurarnos de que todas tengan la misma escala**

In [ ]:
# Escalas las características para un mejor rendimiento del modelo
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


**5. Creamos una instancia de MLPClassifier con una capa oculta de 100 neuronas, función de activación ReLU, algoritmo de optimización 'adam' y un máximo de 500 iteraciones.**

In [ ]:
# Crear uns instancia MLPClassifier
mlp_clf = MLPClassifier(hidden_layer_sizes=(100),
                        activation = 'relu',
                        solver = 'adam',
                        max_iter = 100,
                        random_state=42,
                        verbose=True)

**6. Entrenamos el modelo utilizando los datos de entrenamiento escalados.**

In [ ]:
# Entrenar el modelo
mlp_clf.fit(X_train_scaled, y_train)

Iteration 1, loss = 1.16374923
Iteration 2, loss = 1.14090611
Iteration 3, loss = 1.11857816
Iteration 4, loss = 1.09677375
Iteration 5, loss = 1.07547149
Iteration 6, loss = 1.05468504
Iteration 7, loss = 1.03440573
Iteration 8, loss = 1.01462373
Iteration 9, loss = 0.99535820
Iteration 10, loss = 0.97658926
Iteration 11, loss = 0.95833257
Iteration 12, loss = 0.94053852
Iteration 13, loss = 0.92322169
Iteration 14, loss = 0.90638373
Iteration 15, loss = 0.89000670
Iteration 16, loss = 0.87408395
Iteration 17, loss = 0.85861030
Iteration 18, loss = 0.84357120
Iteration 19, loss = 0.82895431
Iteration 20, loss = 0.81476466
Iteration 21, loss = 0.80097410
Iteration 22, loss = 0.78759157
Iteration 23, loss = 0.77460302
Iteration 24, loss = 0.76199129
Iteration 25, loss = 0.74975377
Iteration 26, loss = 0.73786826
Iteration 27, loss = 0.72632581
Iteration 28, loss = 0.71511871
Iteration 29, loss = 0.70424319
Iteration 30, loss = 0.69368183
Iteration 31, loss = 0.68342580
Iteration 32, los

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=100, max_iter=100, random_state=42,
              verbose=True)

**7. Realizamos predicciones en el conjunto de prueba.**

In [ ]:
y_pred = mlp_clf.predict(X_test_scaled)
print(y_test)
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
[1 0 2 1 2 0 1 2 1 1 2 0 0 0 0 2 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


**8. Calculamos la precisión del modelo utilizando la función accuracy_score**

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("Precisión del modelo", round(accuracy,2))

Precisión del modelo 0.93


# Implementación de Red Neuronal para regresión utilizando MLPRegressor

---

In [ ]:
# Cargamos las librerías a usar

from sklearn.neural_network import MLPRegressor
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

In [ ]:
# Cargar el conjunto de datos de california Housing
housing = fetch_california_housing()
X, y = housing.data, housing.target

# Explorando los datos
type(housing)
housing.keys()
housing['data']
housing['target']
housing['target_names']
housing['DESCR']
housing['feature_names']


['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [ ]:
# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [ ]:
# Escalar las características para un mejor rendimiento del modelo
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Crear uns instancia MLPClassifier
mlp_reg = MLPRegressor(hidden_layer_sizes=(100),
                        activation = 'relu',
                        solver = 'adam',
                        max_iter = 100,
                        random_state=42,
                        verbose=True)

In [ ]:
# Entrenar el modelo
mlp_reg.fit(X_train_scaled, y_train)

Iteration 1, loss = 1.62056447
Iteration 2, loss = 0.43678846
Iteration 3, loss = 0.32700527
Iteration 4, loss = 0.28069940
Iteration 5, loss = 0.24814135
Iteration 6, loss = 0.22803342
Iteration 7, loss = 0.21538976
Iteration 8, loss = 0.20787968
Iteration 9, loss = 0.20154389
Iteration 10, loss = 0.19743378
Iteration 11, loss = 0.19321222
Iteration 12, loss = 0.18961729
Iteration 13, loss = 0.18678600
Iteration 14, loss = 0.18383630
Iteration 15, loss = 0.18157601
Iteration 16, loss = 0.17968086
Iteration 17, loss = 0.17775103
Iteration 18, loss = 0.17538371
Iteration 19, loss = 0.17423819
Iteration 20, loss = 0.17407294
Iteration 21, loss = 0.17085613
Iteration 22, loss = 0.16995187
Iteration 23, loss = 0.16823352
Iteration 24, loss = 0.16798530
Iteration 25, loss = 0.16717835
Iteration 26, loss = 0.16566984
Iteration 27, loss = 0.16730781
Iteration 28, loss = 0.16499618
Iteration 29, loss = 0.16261953
Iteration 30, loss = 0.16145474
Iteration 31, loss = 0.16053131
Iteration 32, los

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(hidden_layer_sizes=100, max_iter=100, random_state=42,
             verbose=True)

In [ ]:
# Realizar predicciones en el conjunto de prueba
y_pred = mlp_reg.predict(X_test_scaled)

In [ ]:
# Calcular el error cuadrático medio del modelo
mse = mean_squared_error(y_test, y_pred)
print("Error cuadrático medio del modelo: ", round(mse,3))

Error cuadrático medio del modelo:  0.329


In [28]:
error = y_test - y_pred
print(error)
error

[ 0.11614674 -0.78451853  0.35386598 ...  0.18160072 -0.07049547
 -0.20138212]


array([ 0.11614674, -0.78451853,  0.35386598, ...,  0.18160072,
       -0.07049547, -0.20138212])

In [29]:
lista = [valor**2  for valor in error]
lista

[0.01349006470162435,
 0.6154693184540858,
 0.12522113302122298,
 0.1732655838184803,
 0.012687375276175736,
 0.002971963237614876,
 0.40170324812355457,
 0.02260041452952433,
 0.6731209340076371,
 1.0523202908625065e-06,
 0.02745796159451556,
 0.34219640195926515,
 0.5092845486763115,
 0.15214947632715303,
 0.09666400273974009,
 0.03857850103654245,
 0.0810354068612068,
 0.10851625242260733,
 0.24328617355833013,
 0.07725156519875023,
 0.05686883095923089,
 0.24995787968700894,
 0.013928759406108625,
 1.2394544918884165,
 0.01658990444476626,
 0.002390853580607302,
 0.4674323596805431,
 0.18643739835071382,
 0.04275905666285562,
 0.18458846035603843,
 0.4620028846543583,
 0.004796594488874464,
 0.268699352082754,
 1.816785844551476,
 0.3651717287279569,
 0.024610209219529004,
 0.30399865863862663,
 2.911526089022133e-06,
 0.013617083398532029,
 0.021064004814224876,
 0.07485261757892558,
 0.0029710373398375055,
 0.17896371442906345,
 8.528537590156832e-05,
 0.00790323358598194,
 0.824

In [32]:
import numpy as np
mse_otro = np.array(lista).mean()
print(round(mse_otro,3))

0.329


In [33]:
def mse_manual (y_prueba, y_predichos):
  error = y_prueba - y_predichos
  lista = [valor**2 for valor in error]
  mse = np.array(lista).mean()
  return round(mse,3)

mse_manual(y_test,y_pred)

0.329